<template>
  <vscode code="" lang="json" :explorer-visible="false">
    <template v-slot:code>
      <pre class="shiki"><code><span class="line"><span style="color: var(--shiki-token-punctuation)">...</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">  {</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">      </span><span style="color: var(--shiki-token-keyword)">"path"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-string-expression)">"packages/case-management/case-config"</span><span style="color: var(--shiki-token-punctuation)">,</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">      </span><span style="color: var(--shiki-token-keyword)">"package"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-string-expression)">"case-config"</span><span style="color: var(--shiki-token-punctuation)">,</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">      </span><span style="color: var(--shiki-token-keyword)">"versionName"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-string-expression)">"case-config-1.0"</span><span style="color: var(--shiki-token-punctuation)">,</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">      </span><span style="color: var(--shiki-token-keyword)">"versionNumber"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-string-expression)">"1.0.6.NEXT"</span><span style="color: var(--shiki-token-punctuation)">,</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">      </span><span style="color: var(--shiki-token-keyword)">"dependencies"</span><span style="color: var(--shiki-token-punctuation)">: [{</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">          </span><span style="color: var(--shiki-token-keyword)">"package"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-string-expression)">"case-management"</span><span style="color: var(--shiki-token-punctuation)">,</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">          </span><span style="color: var(--shiki-token-keyword)">"versionNumber"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-string-expression)">"3.2.0.LATEST"</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">      }]</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">  }, {</span></span>
<span class="line added"><span style="color: var(--shiki-token-punctuation)">      </span><span style="color: var(--shiki-token-keyword)">"path"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-string-expression)">"packages/quote-recalculation-batch"</span><span style="color: var(--shiki-token-punctuation)">,</span></span>
<span class="line added"><span style="color: var(--shiki-token-punctuation)">      </span><span style="color: var(--shiki-token-keyword)">"package"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-string-expression)">"quote-recalculation-batch"</span><span style="color: var(--shiki-token-punctuation)">,</span></span>
<span class="line added"><span style="color: var(--shiki-token-punctuation)">      </span><span style="color: var(--shiki-token-keyword)">"versionName"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-string-expression)">"quote-recalculation-batch-1.2"</span><span style="color: var(--shiki-token-punctuation)">,</span></span>
<span class="line added"><span style="color: var(--shiki-token-punctuation)">      </span><span style="color: var(--shiki-token-keyword)">"versionNumber"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-string-expression)">"1.2.0.NEXT"</span><span style="color: var(--shiki-token-punctuation)">,</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">      </span><span style="color: var(--shiki-token-keyword)">"default"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-keyword)">false</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">  }, {</span></span>
<span class="line added"><span style="color: var(--shiki-token-punctuation)">       </span><span style="color: var(--shiki-token-keyword)">"path"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-string-expression)">"packages/sales/opportunity-management"</span><span style="color: var(--shiki-token-punctuation)">,</span></span>
<span class="line added"><span style="color: var(--shiki-token-punctuation)">       </span><span style="color: var(--shiki-token-keyword)">"package"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-string-expression)">"src-sales"</span><span style="color: var(--shiki-token-punctuation)">,</span></span>
<span class="line added"><span style="color: var(--shiki-token-punctuation)">       </span><span style="color: var(--shiki-token-keyword)">"testSynchronous"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-keyword)">true</span><span style="color: var(--shiki-token-punctuation)">,</span></span>
<span class="line added"><span style="color: var(--shiki-token-punctuation)">       </span><span style="color: var(--shiki-token-keyword)">"versionNumber"</span><span style="color: var(--shiki-token-punctuation)">: </span><span style="color: var(--shiki-token-string-expression)">"2.5.17.0"</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">  },</span></span>
<span class="line"><span style="color: var(--shiki-token-punctuation)">...</span></span></code></pre>
    </template>
  </vscode>
</template>
